apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-redis
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test-redis
  template:
    metadata:
      name: test-redis
      labels:
        app: test-redis
    spec:
      containers:
        - name: test-redis
          image: bitnami/redis
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: test-redis
  labels:
    app: test
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: test-redis
  type: ClusterIP