name: Build and push Docker image

on:
  push:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push image
        run: |
          docker build -t phpapp .
          docker tag phpapp ariel1088/phpapp:$GITHUB_RUN_ID
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
          docker push ariel1088/phpapp:$GITHUB_RUN_ID